In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('supershops.csv')

In [6]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

# Normalization

In [4]:
#Marketing Spend
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [5]:
from sklearn.preprocessing import MinMaxScaler
m = MinMaxScaler() # m = MinMaxScaler(feature_range=(2, 5))

In [6]:
df_mar = m.fit(df[['Marketing Spend']]) # trainging

In [7]:
df_mar

MinMaxScaler()

In [8]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [9]:
df[['Marketing Spend']] = m.transform(df[['Marketing Spend']]) #transforming

In [10]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit
0         0.692617       136897.80  471784.10    Dhaka  192261.83
1         0.983359       151377.59  443898.53      Ctg  191792.06
2         0.927985       101145.55  407934.54  Rangpur  191050.39
3         0.873136       118671.85  383199.62    Dhaka  182901.99
4         0.859438        91391.77  366168.42  Rangpur  166187.94

In [11]:
#fit and transform
df[['Administration']] = m.fit_transform(df[['Administration']]) #fit_transform

In [12]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit
0         0.692617        0.651744  471784.10    Dhaka  192261.83
1         0.983359        0.761972  443898.53      Ctg  191792.06
2         0.927985        0.379579  407934.54  Rangpur  191050.39
3         0.873136        0.512998  383199.62    Dhaka  182901.99
4         0.859438        0.305328  366168.42  Rangpur  166187.94

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Marketing Spend  50 non-null     float64
 1   Administration   50 non-null     float64
 2   Transport        49 non-null     float64
 3   Area             50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [15]:
x = df.drop('Profit', axis=1)
y = df[['Profit']]

In [16]:
x1 = x.copy()
x2 = x.copy()
x3 = x.copy()
x4 = x.copy()
x5 = x.copy()
x6 = x.copy()

# Min Max Scaler using for loop

In [7]:
df = pd.read_csv('supershops.csv')

In [8]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [9]:
df.tail()

Marketing Spend  Administration  Transport     Area    Profit
45          1000.23       124153.04    1903.93    Dhaka  64926.08
46          1315.46       115816.21  297114.46  Rangpur  49490.75
47             0.00       135426.92       0.00      Ctg  42559.73
48           542.05        51743.15       0.00    Dhaka  35673.41
49             0.00       116983.80   45173.06      Ctg  14681.40

In [10]:
df.dtypes

Marketing Spend    float64
Administration     float64
Transport          float64
Area                object
Profit             float64
dtype: object

In [11]:
X = df.iloc[:, [0,1,2]]
Y = df.iloc[:, 4]

In [12]:
X.head()

Marketing Spend  Administration  Transport
0        114523.61       136897.80  471784.10
1        162597.70       151377.59  443898.53
2        153441.51       101145.55  407934.54
3        144372.41       118671.85  383199.62
4        142107.34        91391.77  366168.42

In [13]:
Y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [14]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state=50)

In [16]:
X_train.head()

Marketing Spend  Administration  Transport
23         67532.53       105751.03  304768.73
25         64664.71       139553.16  137962.62
3         144372.41       118671.85  383199.62
39         38558.51        82982.09  174999.30
15        165349.20       122616.84  261776.23

In [17]:
scaler = MinMaxScaler().fit(X_train)

In [18]:
print(scaler)

MinMaxScaler()


In [19]:
scaler.data_min_

array([    0.  , 51283.14,     0.  ])

In [20]:
scaler.data_max_

array([165349.2 , 182645.56, 471784.1 ])

In [21]:
X_train.describe()

Marketing Spend  Administration      Transport
count        37.000000       37.000000      36.000000
mean      74649.290811   120666.798378  205178.838611
std       47232.869081    28503.174656  129350.044809
min           0.000000    51283.140000       0.000000
25%       38558.510000   103057.490000  111393.960000
50%       72107.600000   122616.840000  205832.115000
75%      114523.610000   144135.980000  303681.627500
max      165349.200000   182645.560000  471784.100000

In [22]:
scaler.feature_range

(0, 1)

In [23]:

scaler.transform(X_train)

array([[0.40842369, 0.4146383 , 0.64599195],
       [0.39107967, 0.67195793, 0.29242745],
       [0.87313643, 0.51299839, 0.81223513],
       [0.23319442, 0.24130912, 0.3709309 ],
       [1.        , 0.54302973, 0.55486446],
       [0.16869099, 0.25446874, 0.34861436],
       [0.52264964, 0.77823604,        nan],
       [0.        , 0.50014806, 0.09574943],
       [0.69261666, 0.65174393, 1.        ],
       [0.74590551, 0.43692884, 0.64644319],
       [0.61635061, 0.45150637, 0.48573267],
       [0.47408436, 0.78021012, 0.63532724],
       [0.57246821, 0.71401273, 0.59894835],
       [0.        , 0.64054682, 0.        ],
       [0.46116861, 0.47642362, 0.63305328],
       [0.17390063, 0.51204073, 0.36626005],
       [0.13412668, 0.78807166, 0.06005866],
       [0.45557444, 0.70684477, 0.28413435],
       [0.43609283, 0.58297807, 0.74861321],
       [0.39946683, 1.        , 0.25042853],
       [0.72539353, 0.8013272 , 0.54370828],
       [0.09377566, 0.57930693, 0.07531871],
       [0.

In [24]:
X_train_scaled = scaler.transform(X_train)

In [25]:
print(X_train_scaled)

[[0.40842369 0.4146383  0.64599195]
 [0.39107967 0.67195793 0.29242745]
 [0.87313643 0.51299839 0.81223513]
 [0.23319442 0.24130912 0.3709309 ]
 [1.         0.54302973 0.55486446]
 [0.16869099 0.25446874 0.34861436]
 [0.52264964 0.77823604        nan]
 [0.         0.50014806 0.09574943]
 [0.69261666 0.65174393 1.        ]
 [0.74590551 0.43692884 0.64644319]
 [0.61635061 0.45150637 0.48573267]
 [0.47408436 0.78021012 0.63532724]
 [0.57246821 0.71401273 0.59894835]
 [0.         0.64054682 0.        ]
 [0.46116861 0.47642362 0.63305328]
 [0.17390063 0.51204073 0.36626005]
 [0.13412668 0.78807166 0.06005866]
 [0.45557444 0.70684477 0.28413435]
 [0.43609283 0.58297807 0.74861321]
 [0.39946683 1.         0.25042853]
 [0.72539353 0.8013272  0.54370828]
 [0.09377566 0.57930693 0.07531871]
 [0.7880179  0.71745725 0.68649342]
 [0.36974101 0.77205322 0.18698856]
 [0.92798459 0.37957895 0.8646636 ]
 [0.797566   0.3694479  0.76912588]
 [0.4475048  0.54429273 0.64291963]
 [0.14297577 0.34185188 0.31

In [26]:
scaler = MinMaxScaler().fit(X_test)

In [27]:
print(scaler)

MinMaxScaler()


In [28]:
scaler.data_min_

array([  1315.46,  65947.93, 107138.38])

In [29]:
scaler.data_max_

array([162597.7 , 157693.92, 443898.53])

In [30]:
scaler.feature_range

(0, 1)

In [31]:
X_test.describe()

Marketing Spend  Administration      Transport
count        13.000000       13.000000      13.000000
mean      71081.309231   123273.880000  243447.438462
std       43596.054716    27616.368336   85519.568185
min        1315.460000    65947.930000  107138.380000
25%       46014.020000   114175.790000  201126.820000
50%       77044.010000   127056.210000  249839.440000
75%       91992.390000   148718.950000  294919.570000
max      162597.700000   157693.920000  443898.530000

In [32]:
scaler.transform(X_test)

array([[0.2796998 , 1.        , 0.30781341],
       [0.16956796, 0.66605941, 0.27909609],
       [1.        , 0.93115416, 1.        ],
       [0.11727348, 0.        , 0.23199515],
       [0.73924482, 0.90217589, 0.60718262],
       [0.47554926, 0.60656188, 0.46682388],
       [0.27714496, 0.20817814, 0.29213451],
       [0.56222514, 0.75804011, 0.43213709],
       [0.3986181 , 0.94918732, 0.        ],
       [0.46954054, 0.3633228 , 0.09928856],
       [0.56071704, 0.52566723, 0.55761108],
       [0.        , 0.54354724, 0.56412874],
       [0.57382815, 0.66893877, 0.42374687]])

In [33]:
X_test_scaled = scaler.transform(X_test) 

In [34]:
print(X_test_scaled)

[[0.2796998  1.         0.30781341]
 [0.16956796 0.66605941 0.27909609]
 [1.         0.93115416 1.        ]
 [0.11727348 0.         0.23199515]
 [0.73924482 0.90217589 0.60718262]
 [0.47554926 0.60656188 0.46682388]
 [0.27714496 0.20817814 0.29213451]
 [0.56222514 0.75804011 0.43213709]
 [0.3986181  0.94918732 0.        ]
 [0.46954054 0.3633228  0.09928856]
 [0.56071704 0.52566723 0.55761108]
 [0.         0.54354724 0.56412874]
 [0.57382815 0.66893877 0.42374687]]


# Standard Scaler

In [35]:
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

In [36]:
df.shape

(50, 5)

In [37]:
df.dtypes

Marketing Spend    float64
Administration     float64
Transport          float64
Area                object
Profit             float64
dtype: object

In [38]:
X = df.iloc[:, [0,1,2]]
Y = df.iloc[:, 4]

In [39]:
X.head()

Marketing Spend  Administration  Transport
0        114523.61       136897.80  471784.10
1        162597.70       151377.59  443898.53
2        153441.51       101145.55  407934.54
3        144372.41       118671.85  383199.62
4        142107.34        91391.77  366168.42

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [41]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state = 40)

In [42]:
X_train.head()

Marketing Spend  Administration  Transport
21         78389.47       153773.43  299737.29
44         22177.74       154806.14   28334.72
41         27892.92        84710.77  164470.71
23         67532.53       105751.03  304768.73
36         28663.76       127056.21  201126.82

In [43]:
scaler = StandardScaler().fit(X_train)

In [44]:
print(scaler)

StandardScaler()


In [45]:
scaler.mean_

array([ 74393.67864865, 124931.29702703, 211076.72527778])

In [46]:
scaler.scale_

array([ 44910.78106948,  28204.69094584, 112788.47960309])

In [47]:
scaler.transform(X_train)

array([[ 8.89717626e-02,  1.02260057e+00,  7.86078197e-01],
       [-1.16265933e+00,  1.05921540e+00, -1.62021871e+00],
       [-1.03540303e+00, -1.42602261e+00, -4.13216097e-01],
       [-1.52772864e-01, -6.80038192e-01,  8.30687718e-01],
       [-1.01823922e+00,  7.53389916e-02, -8.82173899e-02],
       [ 1.27994259e+00, -8.90510982e-01,  1.34574591e+00],
       [ 3.91859392e-01,  3.74539575e-01,  3.68727417e-01],
       [-7.97919070e-01, -1.48731312e+00, -3.19867999e-01],
       [ 4.51194142e-01,  7.14288379e-01,  6.33908578e-01],
       [-1.31122076e+00,  8.69005435e-02, -1.55638728e+00],
       [ 5.90132545e-02, -9.09421666e-01, -6.25080820e-01],
       [ 1.55817222e+00, -2.21929290e-01,  1.52606805e+00],
       [-8.88692290e-03, -7.61769392e-02,  8.17836494e-01],
       [-1.01622255e+00, -2.26389541e-01, -3.39405721e-01],
       [ 2.08233152e-02,  6.80903861e-01, -6.82930168e-01],
       [-6.22737080e-01,  1.16160191e+00, -2.47414699e-03],
       [ 4.14194834e-02, -3.92275067e-01

In [48]:
X_train_scaled = scaler.transform(X_train)

In [49]:
print(X_train_scaled)

[[ 8.89717626e-02  1.02260057e+00  7.86078197e-01]
 [-1.16265933e+00  1.05921540e+00 -1.62021871e+00]
 [-1.03540303e+00 -1.42602261e+00 -4.13216097e-01]
 [-1.52772864e-01 -6.80038192e-01  8.30687718e-01]
 [-1.01823922e+00  7.53389916e-02 -8.82173899e-02]
 [ 1.27994259e+00 -8.90510982e-01  1.34574591e+00]
 [ 3.91859392e-01  3.74539575e-01  3.68727417e-01]
 [-7.97919070e-01 -1.48731312e+00 -3.19867999e-01]
 [ 4.51194142e-01  7.14288379e-01  6.33908578e-01]
 [-1.31122076e+00  8.69005435e-02 -1.55638728e+00]
 [ 5.90132545e-02 -9.09421666e-01 -6.25080820e-01]
 [ 1.55817222e+00 -2.21929290e-01  1.52606805e+00]
 [-8.88692290e-03 -7.61769392e-02  8.17836494e-01]
 [-1.01622255e+00 -2.26389541e-01 -3.39405721e-01]
 [ 2.08233152e-02  6.80903861e-01 -6.82930168e-01]
 [-6.22737080e-01  1.16160191e+00 -2.47414699e-03]
 [ 4.14194834e-02 -3.92275067e-01  7.76566410e-01]
 [-1.85749578e-01  2.04626468e+00 -8.23918592e-01]
 [ 1.01422332e+00  1.12095265e+00  4.02844288e-01]
 [ 2.02524915e+00 -8.20592940e-

In [50]:
print(X_train_scaled.mean(axis=0))

[-6.60132609e-17  9.60192886e-16             nan]


In [51]:
print(X_train_scaled.std(axis=0))

[ 1.  1. nan]


In [52]:
X_test.head()

Marketing Spend  Administration  Transport
33         55493.95       103057.49  214634.81
29         65605.48       153032.06  107138.38
49             0.00       116983.80   45173.06
38         20229.59        65947.93  185265.10
45          1000.23       124153.04    1903.93

In [53]:
scaler = StandardScaler().fit(X_test)

In [54]:
scaler.mean_

array([ 71808.82076923, 111136.46076923, 227114.82923077])

In [55]:
scaler.scale_

array([ 46864.26302872,  23534.80955469, 132121.53008265])

In [56]:
scaler.transform(X_test)

array([[-0.34813032, -0.34327751, -0.09445863],
       [-0.13236826,  1.78015459, -0.90807644],
       [-1.53227249,  0.24845492, -1.37707888],
       [-1.10060902, -1.92007208, -0.31675178],
       [-1.51092936,  0.55307774, -1.7045738 ],
       [ 0.91145761,  1.09460581,  1.85185012],
       [ 0.42549136,  0.12914187,  0.51319978],
       [ 1.50004534, -0.8389569 ,  1.05246731],
       [ 0.61588804, -0.82201008,  0.17127958],
       [ 1.74189636, -0.42451632,  1.36858626],
       [ 0.13238849,  0.44449432,  0.28179533],
       [-0.55041516, -1.10852908, -0.16346457],
       [-0.15244261,  1.20743272, -0.67477427]])

In [57]:
X_test_scaled =  scaler.transform(X_test)

In [58]:
print(X_test_scaled)

[[-0.34813032 -0.34327751 -0.09445863]
 [-0.13236826  1.78015459 -0.90807644]
 [-1.53227249  0.24845492 -1.37707888]
 [-1.10060902 -1.92007208 -0.31675178]
 [-1.51092936  0.55307774 -1.7045738 ]
 [ 0.91145761  1.09460581  1.85185012]
 [ 0.42549136  0.12914187  0.51319978]
 [ 1.50004534 -0.8389569   1.05246731]
 [ 0.61588804 -0.82201008  0.17127958]
 [ 1.74189636 -0.42451632  1.36858626]
 [ 0.13238849  0.44449432  0.28179533]
 [-0.55041516 -1.10852908 -0.16346457]
 [-0.15244261  1.20743272 -0.67477427]]


In [59]:
print(X_test_scaled.mean(axis=0))

[ 1.34507790e-16  9.05258774e-16 -1.79343719e-16]


In [60]:
print(X_test_scaled.std(axis=0))

[1. 1. 1.]


# Max abs scaler

In [ ]:
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MaxAbsScaler.html

In [61]:
from sklearn.preprocessing import MaxAbsScaler
from sklearn.model_selection import train_test_split

In [62]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state=50)

In [63]:
X_train.head()

Marketing Spend  Administration  Transport
23         67532.53       105751.03  304768.73
25         64664.71       139553.16  137962.62
3         144372.41       118671.85  383199.62
39         38558.51        82982.09  174999.30
15        165349.20       122616.84  261776.23

In [64]:
scaler = MaxAbsScaler().fit(X_train)

In [65]:
print(scaler)

MaxAbsScaler()


In [66]:
scaler.max_abs_

array([165349.2 , 182645.56, 471784.1 ])

In [67]:
scaler.scale_

array([165349.2 , 182645.56, 471784.1 ])

In [68]:

X_train.describe()

Marketing Spend  Administration      Transport
count        37.000000       37.000000      36.000000
mean      74649.290811   120666.798378  205178.838611
std       47232.869081    28503.174656  129350.044809
min           0.000000    51283.140000       0.000000
25%       38558.510000   103057.490000  111393.960000
50%       72107.600000   122616.840000  205832.115000
75%      114523.610000   144135.980000  303681.627500
max      165349.200000   182645.560000  471784.100000

In [69]:
scaler.transform(X_train)

array([[0.40842369, 0.5789959 , 0.64599195],
       [0.39107967, 0.76406544, 0.29242745],
       [0.87313643, 0.64973849, 0.81223513],
       [0.23319442, 0.45433401, 0.3709309 ],
       [1.        , 0.67133764, 0.55486446],
       [0.16869099, 0.46379868, 0.34861436],
       [0.52264964, 0.84050283,        nan],
       [0.        , 0.64049627, 0.09574943],
       [0.69261666, 0.74952712, 1.        ],
       [0.74590551, 0.59502771, 0.64644319],
       [0.61635061, 0.60551217, 0.48573267],
       [0.47408436, 0.84192263, 0.63532724],
       [0.57246821, 0.79431211, 0.59894835],
       [0.        , 0.74147392, 0.        ],
       [0.46116861, 0.62343317, 0.63305328],
       [0.17390063, 0.64904972, 0.36626005],
       [0.13412668, 0.8475768 , 0.06005866],
       [0.45557444, 0.78915677, 0.28413435],
       [0.43609283, 0.7000693 , 0.74861321],
       [0.39946683, 1.        , 0.25042853],
       [0.72539353, 0.85711046, 0.54370828],
       [0.09377566, 0.69742894, 0.07531871],
       [0.

In [70]:
X_train_scaled = scaler.transform(X_train)

In [71]:
print(X_train_scaled)

[[0.40842369 0.5789959  0.64599195]
 [0.39107967 0.76406544 0.29242745]
 [0.87313643 0.64973849 0.81223513]
 [0.23319442 0.45433401 0.3709309 ]
 [1.         0.67133764 0.55486446]
 [0.16869099 0.46379868 0.34861436]
 [0.52264964 0.84050283        nan]
 [0.         0.64049627 0.09574943]
 [0.69261666 0.74952712 1.        ]
 [0.74590551 0.59502771 0.64644319]
 [0.61635061 0.60551217 0.48573267]
 [0.47408436 0.84192263 0.63532724]
 [0.57246821 0.79431211 0.59894835]
 [0.         0.74147392 0.        ]
 [0.46116861 0.62343317 0.63305328]
 [0.17390063 0.64904972 0.36626005]
 [0.13412668 0.8475768  0.06005866]
 [0.45557444 0.78915677 0.28413435]
 [0.43609283 0.7000693  0.74861321]
 [0.39946683 1.         0.25042853]
 [0.72539353 0.85711046 0.54370828]
 [0.09377566 0.69742894 0.07531871]
 [0.7880179  0.79678948 0.68649342]
 [0.36974101 0.83605602 0.18698856]
 [0.92798459 0.5537805  0.8646636 ]
 [0.797566   0.54649404 0.76912588]
 [0.4475048  0.67224602 0.64291963]
 [0.14297577 0.52664642 0.31

In [72]:
scaler = MaxAbsScaler().fit(X_test)

In [73]:
print(scaler)

MaxAbsScaler()


In [74]:
scaler.max_abs_

array([162597.7 , 157693.92, 443898.53])

In [75]:
scaler.scale_

array([162597.7 , 157693.92, 443898.53])

In [76]:
X_test.describe()

Marketing Spend  Administration      Transport
count        13.000000       13.000000      13.000000
mean      71081.309231   123273.880000  243447.438462
std       43596.054716    27616.368336   85519.568185
min        1315.460000    65947.930000  107138.380000
25%       46014.020000   114175.790000  201126.820000
50%       77044.010000   127056.210000  249839.440000
75%       91992.390000   148718.950000  294919.570000
max      162597.700000   157693.920000  443898.530000

In [77]:
scaler.transform(X_test)

array([[0.28552722, 1.        , 0.47487805],
       [0.17628638, 0.80571407, 0.45309188],
       [1.        , 0.95994563, 1.        ],
       [0.12441498, 0.41820211, 0.41735912],
       [0.7413544 , 0.94308614, 0.70199216],
       [0.47979221, 0.77109853, 0.5955101 ],
       [0.28299306, 0.53931972, 0.46298338],
       [0.56576686, 0.85922824, 0.56919524],
       [0.40348344, 0.97043729, 0.24135782],
       [0.4738321 , 0.62958255, 0.31668231],
       [0.56427096, 0.72403419, 0.6643851 ],
       [0.00809027, 0.73443675, 0.66932968],
       [0.577276  , 0.80738928, 0.56283007]])

In [78]:
X_test_scaled = scaler.transform(X_test)

In [79]:
print(X_test_scaled)

[[0.28552722 1.         0.47487805]
 [0.17628638 0.80571407 0.45309188]
 [1.         0.95994563 1.        ]
 [0.12441498 0.41820211 0.41735912]
 [0.7413544  0.94308614 0.70199216]
 [0.47979221 0.77109853 0.5955101 ]
 [0.28299306 0.53931972 0.46298338]
 [0.56576686 0.85922824 0.56919524]
 [0.40348344 0.97043729 0.24135782]
 [0.4738321  0.62958255 0.31668231]
 [0.56427096 0.72403419 0.6643851 ]
 [0.00809027 0.73443675 0.66932968]
 [0.577276   0.80738928 0.56283007]]


# Robust Scaler

In [ ]:
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.RobustScaler.html

In [80]:
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import train_test_split

In [81]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state = 50)

In [82]:
X_train.head()

Marketing Spend  Administration  Transport
23         67532.53       105751.03  304768.73
25         64664.71       139553.16  137962.62
3         144372.41       118671.85  383199.62
39         38558.51        82982.09  174999.30
15        165349.20       122616.84  261776.23

In [83]:
scaler = RobustScaler().fit(X_train)

In [84]:
print(scaler)

RobustScaler()


In [85]:
scaler.n_features_in_

3

In [86]:
scaler.transform(X_train)

array([[-0.06022595, -0.41057522,  0.51452397],
       [-0.09797776,  0.41229169, -0.35295813],
       [ 0.95128961, -0.09603542,  0.92240708],
       [-0.4416382 , -0.96485411, -0.16034733],
       [ 1.22742681,  0.        ,  0.29093969],
       [-0.58203938, -0.92277175, -0.2151017 ],
       [ 0.18840362,  0.75215204,         nan],
       [-0.9492201 , -0.1371287 , -0.83551409],
       [ 0.5583618 ,  0.34765056,  1.38309434],
       [ 0.67435283, -0.33929363,  0.51563112],
       [ 0.39235754, -0.29267702,  0.12132258],
       [ 0.08269416,  0.75846483,  0.48835776],
       [ 0.29684105,  0.54677618,  0.39910097],
       [-0.9492201 ,  0.31184398, -1.07043846],
       [ 0.05458112, -0.21299566,  0.48277852],
       [-0.57069983, -0.09909785, -0.1718074 ],
       [-0.65727367,  0.78360475, -0.92308257],
       [ 0.0424046 ,  0.52385421, -0.37330551],
       [ 0.        ,  0.12774837,  0.76630861],
       [-0.07972187,  1.46131759, -0.45600384],
       [ 0.62970548,  0.82599385,  0.263

In [87]:
X_train_scaled = scaler.transform(X_train)

In [88]:
print(X_test_scaled)

[[0.28552722 1.         0.47487805]
 [0.17628638 0.80571407 0.45309188]
 [1.         0.95994563 1.        ]
 [0.12441498 0.41820211 0.41735912]
 [0.7413544  0.94308614 0.70199216]
 [0.47979221 0.77109853 0.5955101 ]
 [0.28299306 0.53931972 0.46298338]
 [0.56576686 0.85922824 0.56919524]
 [0.40348344 0.97043729 0.24135782]
 [0.4738321  0.62958255 0.31668231]
 [0.56427096 0.72403419 0.6643851 ]
 [0.00809027 0.73443675 0.66932968]
 [0.577276   0.80738928 0.56283007]]


In [89]:
scaler = RobustScaler().fit(X_test)

In [90]:
scaler.transform(X_test)

array([[-0.66592052,  0.88693999, -0.41625573],
       [-1.05223935,  0.        , -0.51936445],
       [ 1.86073778,  0.70408671,  2.06902015],
       [-1.23567712, -1.7690414 , -0.68847901],
       [ 0.94606464,  0.62712097,  0.65862074],
       [ 0.0210773 , -0.15802434,  0.15466675],
       [-0.67488234, -1.21612412, -0.47255038],
       [ 0.32511766,  0.24429902,  0.03012482],
       [-0.24878068,  0.75198245, -1.52145086],
       [ 0.        , -0.8040628 , -1.16495817],
       [ 0.31982756, -0.37287903,  0.48063555],
       [-1.6470473 , -0.32539003,  0.50403704],
       [ 0.36581854,  0.00764753,  0.        ]])

In [91]:
X_test_scaled = scaler.transform(X_test)

In [92]:
print(X_test_scaled)

[[-0.66592052  0.88693999 -0.41625573]
 [-1.05223935  0.         -0.51936445]
 [ 1.86073778  0.70408671  2.06902015]
 [-1.23567712 -1.7690414  -0.68847901]
 [ 0.94606464  0.62712097  0.65862074]
 [ 0.0210773  -0.15802434  0.15466675]
 [-0.67488234 -1.21612412 -0.47255038]
 [ 0.32511766  0.24429902  0.03012482]
 [-0.24878068  0.75198245 -1.52145086]
 [ 0.         -0.8040628  -1.16495817]
 [ 0.31982756 -0.37287903  0.48063555]
 [-1.6470473  -0.32539003  0.50403704]
 [ 0.36581854  0.00764753  0.        ]]
